MAJOR=0
MINOR=8
MICRO=0

enables = []

def save():
        f=open("version.h","wb")
        f.write("/* version.h - Generated by version.py */\n");
        f.write("#ifndef VERSION_H\n");
        f.write("#define VERSION_H\n");

        f.write("\n\n");
        f.write("#define VERSION_MAJOR "+str(MAJOR)+"\n");
        f.write("#define VERSION_MINOR "+str(MINOR)+"\n");
        f.write("#define VERSION_MICRO "+str(MICRO)+"\n");
        f.write("#define VERSION_INT (VERSION_MAJOR*10000+VERSION_MINOR*100+VERSION_MICRO)\n");
        f.write("#define VERSION_STRING \""+str(MAJOR)+"."+str(MINOR)+"."+str(MICRO)+"\"\n");
        f.write("\n\n");

        for flg in enables:
                f.write("#define "+flg+"\n");
        f.write("\n\n");  
        f.write("#endif\n");
        f.close();
