
import os;
import glob;
import string;

pixmaps = glob.glob("*.xpm");

pixmaps.sort();


#Generate include files
print '// THIS FILE HAS BEEN AUTOGENERATED, DONT EDIT!!'
print '#include "visual_settings.h"'
print '';
for x in pixmaps:
	
	print '#include "pixmaps/default_skin/'+x+'"';
	
	
print '';
print 'namespace ReShaked {';

print 'void VisualSettings::load_default_theme_pixmaps() {';
print '';

for x in pixmaps:
	
	theme_str='THEME_'+x[:-4].upper();
	var_str=x.replace(".","_");
	print '    pixmap_map['+theme_str+']=QPixmap( (const char**) '+var_str+'); ';
	print '    pixmap_map_skin["'+var_str[:-4]+'"]='+theme_str+';';

print '';

print '}';

print '';
	
print '} //end of namespace';

print '';
	