
EnsureSConsVersion(0,96);

import detect;
import sys;
import os;

import version


# PRE-detect Qt3 QTDIR

QT_VERSION_MAJOR_NEEDED = 4
QT_VERSION_MINOR_NEEDED = 0

qtdir=detect.check_qtdir(QT_VERSION_MAJOR_NEEDED,QT_VERSION_MINOR_NEEDED);
os.environ["QTDIR"]=qtdir;

env = Environment(CPPFLAGS=['-g3','-Wall','-Wno-sign-compare'],tools=['default','qt'], ENV={'PATH' : os.environ['PATH']});

env.use_asio=False;

print env['TOOLS']

if (os.name=='nt'): #WINDOWS

	env.Append(LIBS=['QtGui4','QtCore4','dsound','winmm','ole32']);
	version.enables+=['WIN32_ENABLED'];

else: #POSIX
	env.Append(LIBS=['QtGui','QtCore']);
	env.Append(LIBS=['pthread']);
	version.enables+=['POSIX_ENABLED'];
	version.enables+=['LADSPA_ENABLED'];
	detect.check_pkg_config();


#version.enables+=['DRIVER_RTAUDIO_ENABLED'];
version.enables+=['DRIVER_PORTAUDIO_ENABLED'];


#env.Append(CXXFLAGS=['-DQT_NO_KEYWORDS']);
#env.Append(CPPPATH=['#types/','#engine/','#interface/','#ui_blocks/']);
env.Append(CPPPATH=['#','#types/','#engine/','#interface/','#ui_blocks/','#pixmaps/','#editor/']);
env["QT_LIB"]="";
#Enable the make_targets helper
#env.__class__.make_targets = detect.make_targets
env.build_dir = None

env.__class__.find_source_files = detect.find_source_files

#detect.check_pkg(env,"qt-mt","3.2");
if (detect.check_pkg(env,"sndfile","1.0.10")):
	version.enables+=['SNDFILE_ENABLED'];

if (detect.check_pkg(env,"jack","0.100.0")):
	version.enables+=['DRIVER_JACK_ENABLED'];

if (detect.check_pkg(env,"alsa","1.0.0")):
	version.enables+=['DRIVER_ALSA_ENABLED'];

Export('env');

version.save();

SConscript('types/SCsub');
SConscript('dsp/SCsub');
SConscript('engine/SCsub');
SConscript('editor/SCsub');
SConscript('interface/SCsub');
SConscript('ui_blocks/SCsub');
SConscript('drivers/SCsub');
SConscript('plugins/SCsub');
SConscript('plugin_UIs/SCsub');
SConscript('program/SCsub');
