// THIS FILE HAS BEEN AUTOGENERATED, DONT EDIT!!
#include "visual_settings.h"

#include "pixmaps/default_skin/bottom__begin.xpm"
#include "pixmaps/default_skin/bottom__end.xpm"
#include "pixmaps/default_skin/bottom__information_begin.xpm"
#include "pixmaps/default_skin/bottom__information_end.xpm"
#include "pixmaps/default_skin/bottom__information_label.xpm"
#include "pixmaps/default_skin/bottom__information_label_bottom.xpm"
#include "pixmaps/default_skin/bottom__information_label_end.xpm"
#include "pixmaps/default_skin/bottom__information_label_top.xpm"
#include "pixmaps/default_skin/bottom__margin.xpm"
#include "pixmaps/default_skin/bottom__octave_bottom.xpm"
#include "pixmaps/default_skin/bottom__octave_label.xpm"
#include "pixmaps/default_skin/bottom__octave_spin.xpm"
#include "pixmaps/default_skin/bottom__octave_top.xpm"
#include "pixmaps/default_skin/bottom__rack.xpm"
#include "pixmaps/default_skin/bottom__rack_active.xpm"
#include "pixmaps/default_skin/bottom__separator.xpm"
#include "pixmaps/default_skin/bottom__time_begin.xpm"
#include "pixmaps/default_skin/bottom__time_end.xpm"
#include "pixmaps/default_skin/bottom__time_label.xpm"
#include "pixmaps/default_skin/bottom__time_label_bottom.xpm"
#include "pixmaps/default_skin/bottom__time_label_top.xpm"
#include "pixmaps/default_skin/bottom__vpiano_begin.xpm"
#include "pixmaps/default_skin/bottom__vpiano_black_key.xpm"
#include "pixmaps/default_skin/bottom__vpiano_black_key_pressed.xpm"
#include "pixmaps/default_skin/bottom__vpiano_octave_separator.xpm"
#include "pixmaps/default_skin/bottom__vpiano_top.xpm"
#include "pixmaps/default_skin/bottom__vpiano_white_key.xpm"
#include "pixmaps/default_skin/bottom__vpiano_white_key_pressed.xpm"
#include "pixmaps/default_skin/bottom_left__corner.xpm"
#include "pixmaps/default_skin/bottom_right__corner.xpm"
#include "pixmaps/default_skin/edit_toolbar__automation_mode_envelope.xpm"
#include "pixmaps/default_skin/edit_toolbar__automation_mode_envelope_active.xpm"
#include "pixmaps/default_skin/edit_toolbar__automation_mode_stream.xpm"
#include "pixmaps/default_skin/edit_toolbar__automation_mode_stream_active.xpm"
#include "pixmaps/default_skin/edit_toolbar__begin.xpm"
#include "pixmaps/default_skin/edit_toolbar__cursor_follows_playback.xpm"
#include "pixmaps/default_skin/edit_toolbar__cursor_follows_playback_pushed.xpm"
#include "pixmaps/default_skin/edit_toolbar__cursor_stepping_dropdown.xpm"
#include "pixmaps/default_skin/edit_toolbar__cursor_stepping_dropdown_bottom.xpm"
#include "pixmaps/default_skin/edit_toolbar__cursor_stepping_dropdown_top.xpm"
#include "pixmaps/default_skin/edit_toolbar__cursor_stepping_icon.xpm"
#include "pixmaps/default_skin/edit_toolbar__edit_menu.xpm"
#include "pixmaps/default_skin/edit_toolbar__edit_menu_bottom.xpm"
#include "pixmaps/default_skin/edit_toolbar__edit_menu_top.xpm"
#include "pixmaps/default_skin/edit_toolbar__end.xpm"
#include "pixmaps/default_skin/edit_toolbar__midi_in_config.xpm"
#include "pixmaps/default_skin/edit_toolbar__midi_in_config_pushed.xpm"
#include "pixmaps/default_skin/edit_toolbar__play_current_block.xpm"
#include "pixmaps/default_skin/edit_toolbar__play_current_block_pushed.xpm"
#include "pixmaps/default_skin/edit_toolbar__play_from_cursor.xpm"
#include "pixmaps/default_skin/edit_toolbar__play_from_cursor_pushed.xpm"
#include "pixmaps/default_skin/edit_toolbar__poly.xpm"
#include "pixmaps/default_skin/edit_toolbar__poly_active.xpm"
#include "pixmaps/default_skin/edit_toolbar__separator.xpm"
#include "pixmaps/default_skin/edit_toolbar__snap_dropdown.xpm"
#include "pixmaps/default_skin/edit_toolbar__snap_dropdown_bottom.xpm"
#include "pixmaps/default_skin/edit_toolbar__snap_dropdown_top.xpm"
#include "pixmaps/default_skin/edit_toolbar__spacer.xpm"
#include "pixmaps/default_skin/edit_toolbar__volume_mask.xpm"
#include "pixmaps/default_skin/edit_toolbar__volume_mask_active.xpm"
#include "pixmaps/default_skin/edit_toolbar__volume_mask_label.xpm"
#include "pixmaps/default_skin/edit_toolbar__volume_mask_label_bottom.xpm"
#include "pixmaps/default_skin/edit_toolbar__volume_mask_label_top.xpm"
#include "pixmaps/default_skin/effect_panel_generic_bottom.xpm"
#include "pixmaps/default_skin/effect_panel_generic_bottom_left.xpm"
#include "pixmaps/default_skin/effect_panel_generic_bottom_right.xpm"
#include "pixmaps/default_skin/effect_panel_generic_label.xpm"
#include "pixmaps/default_skin/effect_panel_generic_left.xpm"
#include "pixmaps/default_skin/effect_panel_generic_right.xpm"
#include "pixmaps/default_skin/effect_panel_generic_slider_base.xpm"
#include "pixmaps/default_skin/effect_panel_generic_slider_grabber.xpm"
#include "pixmaps/default_skin/effect_panel_generic_slider_light.xpm"
#include "pixmaps/default_skin/effect_panel_generic_top.xpm"
#include "pixmaps/default_skin/effect_panel_generic_top_left.xpm"
#include "pixmaps/default_skin/effect_panel_generic_top_right.xpm"
#include "pixmaps/default_skin/effect_panel_generic_value.xpm"
#include "pixmaps/default_skin/effect_panel_generic_vu_empty.xpm"
#include "pixmaps/default_skin/effect_panel_generic_vu_fill.xpm"
#include "pixmaps/default_skin/global_toolbar__add.xpm"
#include "pixmaps/default_skin/global_toolbar__add_active.xpm"
#include "pixmaps/default_skin/global_toolbar__bottom_right_pixmap.xpm"
#include "pixmaps/default_skin/global_toolbar__copy.xpm"
#include "pixmaps/default_skin/global_toolbar__copy_active.xpm"
#include "pixmaps/default_skin/global_toolbar__copy_link.xpm"
#include "pixmaps/default_skin/global_toolbar__copy_link_active.xpm"
#include "pixmaps/default_skin/global_toolbar__eraser.xpm"
#include "pixmaps/default_skin/global_toolbar__eraser_pushed.xpm"
#include "pixmaps/default_skin/global_toolbar__hspacer.xpm"
#include "pixmaps/default_skin/global_toolbar__left.xpm"
#include "pixmaps/default_skin/global_toolbar__right.xpm"
#include "pixmaps/default_skin/global_toolbar__select.xpm"
#include "pixmaps/default_skin/global_toolbar__select_active.xpm"
#include "pixmaps/default_skin/global_toolbar__select_linked.xpm"
#include "pixmaps/default_skin/global_toolbar__select_linked_pushed.xpm"
#include "pixmaps/default_skin/global_toolbar__unlink_selected.xpm"
#include "pixmaps/default_skin/global_toolbar__unlink_selected_pushed.xpm"
#include "pixmaps/default_skin/global_toolbar__zoom_bg.xpm"
#include "pixmaps/default_skin/global_toolbar__zoom_fg.xpm"
#include "pixmaps/default_skin/global_toolbar__zoom_grabber.xpm"
#include "pixmaps/default_skin/global_toolbar__zoom_icon.xpm"
#include "pixmaps/default_skin/left__margin.xpm"
#include "pixmaps/default_skin/middle__separator_begin.xpm"
#include "pixmaps/default_skin/middle__separator_center.xpm"
#include "pixmaps/default_skin/middle__separator_end.xpm"
#include "pixmaps/default_skin/middle_separator_end.xpm"
#include "pixmaps/default_skin/rack_panel__jack_forbidden.xpm"
#include "pixmaps/default_skin/rack_panel__jack_in.xpm"
#include "pixmaps/default_skin/rack_panel__jack_out.xpm"
#include "pixmaps/default_skin/rack_plugin_top__begin.xpm"
#include "pixmaps/default_skin/rack_plugin_top__end.xpm"
#include "pixmaps/default_skin/rack_plugin_top__info.xpm"
#include "pixmaps/default_skin/rack_plugin_top__info_pushed.xpm"
#include "pixmaps/default_skin/rack_plugin_top__move_left.xpm"
#include "pixmaps/default_skin/rack_plugin_top__move_left_pushed.xpm"
#include "pixmaps/default_skin/rack_plugin_top__move_right.xpm"
#include "pixmaps/default_skin/rack_plugin_top__move_right_pushed.xpm"
#include "pixmaps/default_skin/rack_plugin_top__preset.xpm"
#include "pixmaps/default_skin/rack_plugin_top__preset_name.xpm"
#include "pixmaps/default_skin/rack_plugin_top__preset_pushed.xpm"
#include "pixmaps/default_skin/rack_plugin_top__remove.xpm"
#include "pixmaps/default_skin/rack_plugin_top__remove_pushed.xpm"
#include "pixmaps/default_skin/rack_plugin_top__separator.xpm"
#include "pixmaps/default_skin/rack_plugin_top__skip.xpm"
#include "pixmaps/default_skin/rack_plugin_top__skip_active.xpm"
#include "pixmaps/default_skin/rack_toolbar__add_plugin.xpm"
#include "pixmaps/default_skin/rack_toolbar__add_plugin_pushed.xpm"
#include "pixmaps/default_skin/rack_toolbar__begin.xpm"
#include "pixmaps/default_skin/rack_toolbar__end.xpm"
#include "pixmaps/default_skin/rack_toolbar__preset_file.xpm"
#include "pixmaps/default_skin/rack_toolbar__preset_file_pushed.xpm"
#include "pixmaps/default_skin/rack_toolbar__preset_icon.xpm"
#include "pixmaps/default_skin/rack_toolbar__preset_label.xpm"
#include "pixmaps/default_skin/rack_toolbar__preset_label_bottom.xpm"
#include "pixmaps/default_skin/rack_toolbar__preset_label_top.xpm"
#include "pixmaps/default_skin/rack_toolbar__rack_follow_cursor.xpm"
#include "pixmaps/default_skin/rack_toolbar__rack_follow_cursor_active.xpm"
#include "pixmaps/default_skin/rack_toolbar__separator.xpm"
#include "pixmaps/default_skin/rack_toolbar__show_back.xpm"
#include "pixmaps/default_skin/rack_toolbar__show_back_active.xpm"
#include "pixmaps/default_skin/rack_toolbar__show_front.xpm"
#include "pixmaps/default_skin/rack_toolbar__show_front_active.xpm"
#include "pixmaps/default_skin/rack_toolbar__spacer.xpm"
#include "pixmaps/default_skin/rack_toolbar__track_dropdown.xpm"
#include "pixmaps/default_skin/rack_toolbar__track_dropdown_bottom.xpm"
#include "pixmaps/default_skin/rack_toolbar__track_dropdown_top.xpm"
#include "pixmaps/default_skin/right__margin.xpm"
#include "pixmaps/default_skin/scrollbar_arrow_down.xpm"
#include "pixmaps/default_skin/scrollbar_arrow_down_pushed.xpm"
#include "pixmaps/default_skin/scrollbar_arrow_left.xpm"
#include "pixmaps/default_skin/scrollbar_arrow_left_pushed.xpm"
#include "pixmaps/default_skin/scrollbar_arrow_right.xpm"
#include "pixmaps/default_skin/scrollbar_arrow_right_pushed.xpm"
#include "pixmaps/default_skin/scrollbar_arrow_up.xpm"
#include "pixmaps/default_skin/scrollbar_arrow_up_pushed.xpm"
#include "pixmaps/default_skin/scrollbar_grabber.xpm"
#include "pixmaps/default_skin/scrollbar_h_bg.xpm"
#include "pixmaps/default_skin/scrollbar_v_bg.xpm"
#include "pixmaps/default_skin/simpler__bottom.xpm"
#include "pixmaps/default_skin/simpler__display_bottom.xpm"
#include "pixmaps/default_skin/simpler__display_left.xpm"
#include "pixmaps/default_skin/simpler__display_right.xpm"
#include "pixmaps/default_skin/simpler__edit.xpm"
#include "pixmaps/default_skin/simpler__edit_pushed.xpm"
#include "pixmaps/default_skin/simpler__knob.xpm"
#include "pixmaps/default_skin/simpler__knob_pos.xpm"
#include "pixmaps/default_skin/simpler__knob_separator.xpm"
#include "pixmaps/default_skin/simpler__left.xpm"
#include "pixmaps/default_skin/simpler__load.xpm"
#include "pixmaps/default_skin/simpler__load_pushed.xpm"
#include "pixmaps/default_skin/simpler__right.xpm"
#include "pixmaps/default_skin/simpler__top_left.xpm"
#include "pixmaps/default_skin/simpler__top_right.xpm"
#include "pixmaps/default_skin/top__bpm_bottom.xpm"
#include "pixmaps/default_skin/top__bpm_display.xpm"
#include "pixmaps/default_skin/top__bpm_end.xpm"
#include "pixmaps/default_skin/top__bpm_top.xpm"
#include "pixmaps/default_skin/top__bpm_updown.xpm"
#include "pixmaps/default_skin/top__button_fastforward.xpm"
#include "pixmaps/default_skin/top__button_fastforward_active.xpm"
#include "pixmaps/default_skin/top__button_loop.xpm"
#include "pixmaps/default_skin/top__button_loop_active.xpm"
#include "pixmaps/default_skin/top__button_pause.xpm"
#include "pixmaps/default_skin/top__button_pause_active.xpm"
#include "pixmaps/default_skin/top__button_play.xpm"
#include "pixmaps/default_skin/top__button_play_active.xpm"
#include "pixmaps/default_skin/top__button_record.xpm"
#include "pixmaps/default_skin/top__button_record_active.xpm"
#include "pixmaps/default_skin/top__button_record_automations.xpm"
#include "pixmaps/default_skin/top__button_record_automations_active.xpm"
#include "pixmaps/default_skin/top__button_rewind.xpm"
#include "pixmaps/default_skin/top__button_rewind_active.xpm"
#include "pixmaps/default_skin/top__button_stop.xpm"
#include "pixmaps/default_skin/top__button_stop_active.xpm"
#include "pixmaps/default_skin/top__buttons_bottom.xpm"
#include "pixmaps/default_skin/top__buttons_bpm_separator.xpm"
#include "pixmaps/default_skin/top__buttons_top.xpm"
#include "pixmaps/default_skin/top__controls_end.xpm"
#include "pixmaps/default_skin/top__icon_add.xpm"
#include "pixmaps/default_skin/top__icon_add_activated.xpm"
#include "pixmaps/default_skin/top__icon_file.xpm"
#include "pixmaps/default_skin/top__icon_file_activated.xpm"
#include "pixmaps/default_skin/top__icon_help.xpm"
#include "pixmaps/default_skin/top__icon_help_activated.xpm"
#include "pixmaps/default_skin/top__icon_redo.xpm"
#include "pixmaps/default_skin/top__icon_redo_activated.xpm"
#include "pixmaps/default_skin/top__icon_redo_disabled.xpm"
#include "pixmaps/default_skin/top__icon_settings.xpm"
#include "pixmaps/default_skin/top__icon_settings_activated.xpm"
#include "pixmaps/default_skin/top__icon_undo.xpm"
#include "pixmaps/default_skin/top__icon_undo_activated.xpm"
#include "pixmaps/default_skin/top__icon_undo_disabled.xpm"
#include "pixmaps/default_skin/top__margin_bottom.xpm"
#include "pixmaps/default_skin/top__margin_left.xpm"
#include "pixmaps/default_skin/top__margin_right.xpm"
#include "pixmaps/default_skin/top__swing_begin.xpm"
#include "pixmaps/default_skin/top__swing_bottom.xpm"
#include "pixmaps/default_skin/top__swing_end.xpm"
#include "pixmaps/default_skin/top__swing_knob.xpm"
#include "pixmaps/default_skin/top__swing_knob_pos.xpm"
#include "pixmaps/default_skin/top__swing_top.xpm"
#include "pixmaps/default_skin/top__tab_edit.xpm"
#include "pixmaps/default_skin/top__tab_edit_active.xpm"
#include "pixmaps/default_skin/top__tab_mix.xpm"
#include "pixmaps/default_skin/top__tab_mix_active.xpm"
#include "pixmaps/default_skin/top__tab_song.xpm"
#include "pixmaps/default_skin/top__tab_song_active.xpm"
#include "pixmaps/default_skin/top__tabs_buttons_separator.xpm"
#include "pixmaps/default_skin/track_panel__label_bottom.xpm"
#include "pixmaps/default_skin/track_panel__swing_base.xpm"
#include "pixmaps/default_skin/track_panel__swing_bottom.xpm"
#include "pixmaps/default_skin/track_panel__swing_combo.xpm"
#include "pixmaps/default_skin/track_panel__swing_knob.xpm"
#include "pixmaps/default_skin/track_panel__swing_knob_pos.xpm"
#include "pixmaps/default_skin/track_panel__swing_label.xpm"
#include "pixmaps/default_skin/track_panel__swing_local.xpm"
#include "pixmaps/default_skin/track_panel__swing_local_off.xpm"
#include "pixmaps/default_skin/track_panel__swing_local_on.xpm"
#include "pixmaps/default_skin/track_panel__swing_value.xpm"

namespace ReShaked {
void VisualSettings::load_default_theme_pixmaps() {

    pixmap_map[THEME_BOTTOM__BEGIN]=QPixmap( (const char**) bottom__begin_xpm); 
    pixmap_map_skin["bottom__begin"]=THEME_BOTTOM__BEGIN;
    pixmap_map[THEME_BOTTOM__END]=QPixmap( (const char**) bottom__end_xpm); 
    pixmap_map_skin["bottom__end"]=THEME_BOTTOM__END;
    pixmap_map[THEME_BOTTOM__INFORMATION_BEGIN]=QPixmap( (const char**) bottom__information_begin_xpm); 
    pixmap_map_skin["bottom__information_begin"]=THEME_BOTTOM__INFORMATION_BEGIN;
    pixmap_map[THEME_BOTTOM__INFORMATION_END]=QPixmap( (const char**) bottom__information_end_xpm); 
    pixmap_map_skin["bottom__information_end"]=THEME_BOTTOM__INFORMATION_END;
    pixmap_map[THEME_BOTTOM__INFORMATION_LABEL]=QPixmap( (const char**) bottom__information_label_xpm); 
    pixmap_map_skin["bottom__information_label"]=THEME_BOTTOM__INFORMATION_LABEL;
    pixmap_map[THEME_BOTTOM__INFORMATION_LABEL_BOTTOM]=QPixmap( (const char**) bottom__information_label_bottom_xpm); 
    pixmap_map_skin["bottom__information_label_bottom"]=THEME_BOTTOM__INFORMATION_LABEL_BOTTOM;
    pixmap_map[THEME_BOTTOM__INFORMATION_LABEL_END]=QPixmap( (const char**) bottom__information_label_end_xpm); 
    pixmap_map_skin["bottom__information_label_end"]=THEME_BOTTOM__INFORMATION_LABEL_END;
    pixmap_map[THEME_BOTTOM__INFORMATION_LABEL_TOP]=QPixmap( (const char**) bottom__information_label_top_xpm); 
    pixmap_map_skin["bottom__information_label_top"]=THEME_BOTTOM__INFORMATION_LABEL_TOP;
    pixmap_map[THEME_BOTTOM__MARGIN]=QPixmap( (const char**) bottom__margin_xpm); 
    pixmap_map_skin["bottom__margin"]=THEME_BOTTOM__MARGIN;
    pixmap_map[THEME_BOTTOM__OCTAVE_BOTTOM]=QPixmap( (const char**) bottom__octave_bottom_xpm); 
    pixmap_map_skin["bottom__octave_bottom"]=THEME_BOTTOM__OCTAVE_BOTTOM;
    pixmap_map[THEME_BOTTOM__OCTAVE_LABEL]=QPixmap( (const char**) bottom__octave_label_xpm); 
    pixmap_map_skin["bottom__octave_label"]=THEME_BOTTOM__OCTAVE_LABEL;
    pixmap_map[THEME_BOTTOM__OCTAVE_SPIN]=QPixmap( (const char**) bottom__octave_spin_xpm); 
    pixmap_map_skin["bottom__octave_spin"]=THEME_BOTTOM__OCTAVE_SPIN;
    pixmap_map[THEME_BOTTOM__OCTAVE_TOP]=QPixmap( (const char**) bottom__octave_top_xpm); 
    pixmap_map_skin["bottom__octave_top"]=THEME_BOTTOM__OCTAVE_TOP;
    pixmap_map[THEME_BOTTOM__RACK]=QPixmap( (const char**) bottom__rack_xpm); 
    pixmap_map_skin["bottom__rack"]=THEME_BOTTOM__RACK;
    pixmap_map[THEME_BOTTOM__RACK_ACTIVE]=QPixmap( (const char**) bottom__rack_active_xpm); 
    pixmap_map_skin["bottom__rack_active"]=THEME_BOTTOM__RACK_ACTIVE;
    pixmap_map[THEME_BOTTOM__SEPARATOR]=QPixmap( (const char**) bottom__separator_xpm); 
    pixmap_map_skin["bottom__separator"]=THEME_BOTTOM__SEPARATOR;
    pixmap_map[THEME_BOTTOM__TIME_BEGIN]=QPixmap( (const char**) bottom__time_begin_xpm); 
    pixmap_map_skin["bottom__time_begin"]=THEME_BOTTOM__TIME_BEGIN;
    pixmap_map[THEME_BOTTOM__TIME_END]=QPixmap( (const char**) bottom__time_end_xpm); 
    pixmap_map_skin["bottom__time_end"]=THEME_BOTTOM__TIME_END;
    pixmap_map[THEME_BOTTOM__TIME_LABEL]=QPixmap( (const char**) bottom__time_label_xpm); 
    pixmap_map_skin["bottom__time_label"]=THEME_BOTTOM__TIME_LABEL;
    pixmap_map[THEME_BOTTOM__TIME_LABEL_BOTTOM]=QPixmap( (const char**) bottom__time_label_bottom_xpm); 
    pixmap_map_skin["bottom__time_label_bottom"]=THEME_BOTTOM__TIME_LABEL_BOTTOM;
    pixmap_map[THEME_BOTTOM__TIME_LABEL_TOP]=QPixmap( (const char**) bottom__time_label_top_xpm); 
    pixmap_map_skin["bottom__time_label_top"]=THEME_BOTTOM__TIME_LABEL_TOP;
    pixmap_map[THEME_BOTTOM__VPIANO_BEGIN]=QPixmap( (const char**) bottom__vpiano_begin_xpm); 
    pixmap_map_skin["bottom__vpiano_begin"]=THEME_BOTTOM__VPIANO_BEGIN;
    pixmap_map[THEME_BOTTOM__VPIANO_BLACK_KEY]=QPixmap( (const char**) bottom__vpiano_black_key_xpm); 
    pixmap_map_skin["bottom__vpiano_black_key"]=THEME_BOTTOM__VPIANO_BLACK_KEY;
    pixmap_map[THEME_BOTTOM__VPIANO_BLACK_KEY_PRESSED]=QPixmap( (const char**) bottom__vpiano_black_key_pressed_xpm); 
    pixmap_map_skin["bottom__vpiano_black_key_pressed"]=THEME_BOTTOM__VPIANO_BLACK_KEY_PRESSED;
    pixmap_map[THEME_BOTTOM__VPIANO_OCTAVE_SEPARATOR]=QPixmap( (const char**) bottom__vpiano_octave_separator_xpm); 
    pixmap_map_skin["bottom__vpiano_octave_separator"]=THEME_BOTTOM__VPIANO_OCTAVE_SEPARATOR;
    pixmap_map[THEME_BOTTOM__VPIANO_TOP]=QPixmap( (const char**) bottom__vpiano_top_xpm); 
    pixmap_map_skin["bottom__vpiano_top"]=THEME_BOTTOM__VPIANO_TOP;
    pixmap_map[THEME_BOTTOM__VPIANO_WHITE_KEY]=QPixmap( (const char**) bottom__vpiano_white_key_xpm); 
    pixmap_map_skin["bottom__vpiano_white_key"]=THEME_BOTTOM__VPIANO_WHITE_KEY;
    pixmap_map[THEME_BOTTOM__VPIANO_WHITE_KEY_PRESSED]=QPixmap( (const char**) bottom__vpiano_white_key_pressed_xpm); 
    pixmap_map_skin["bottom__vpiano_white_key_pressed"]=THEME_BOTTOM__VPIANO_WHITE_KEY_PRESSED;
    pixmap_map[THEME_BOTTOM_LEFT__CORNER]=QPixmap( (const char**) bottom_left__corner_xpm); 
    pixmap_map_skin["bottom_left__corner"]=THEME_BOTTOM_LEFT__CORNER;
    pixmap_map[THEME_BOTTOM_RIGHT__CORNER]=QPixmap( (const char**) bottom_right__corner_xpm); 
    pixmap_map_skin["bottom_right__corner"]=THEME_BOTTOM_RIGHT__CORNER;
    pixmap_map[THEME_EDIT_TOOLBAR__AUTOMATION_MODE_ENVELOPE]=QPixmap( (const char**) edit_toolbar__automation_mode_envelope_xpm); 
    pixmap_map_skin["edit_toolbar__automation_mode_envelope"]=THEME_EDIT_TOOLBAR__AUTOMATION_MODE_ENVELOPE;
    pixmap_map[THEME_EDIT_TOOLBAR__AUTOMATION_MODE_ENVELOPE_ACTIVE]=QPixmap( (const char**) edit_toolbar__automation_mode_envelope_active_xpm); 
    pixmap_map_skin["edit_toolbar__automation_mode_envelope_active"]=THEME_EDIT_TOOLBAR__AUTOMATION_MODE_ENVELOPE_ACTIVE;
    pixmap_map[THEME_EDIT_TOOLBAR__AUTOMATION_MODE_STREAM]=QPixmap( (const char**) edit_toolbar__automation_mode_stream_xpm); 
    pixmap_map_skin["edit_toolbar__automation_mode_stream"]=THEME_EDIT_TOOLBAR__AUTOMATION_MODE_STREAM;
    pixmap_map[THEME_EDIT_TOOLBAR__AUTOMATION_MODE_STREAM_ACTIVE]=QPixmap( (const char**) edit_toolbar__automation_mode_stream_active_xpm); 
    pixmap_map_skin["edit_toolbar__automation_mode_stream_active"]=THEME_EDIT_TOOLBAR__AUTOMATION_MODE_STREAM_ACTIVE;
    pixmap_map[THEME_EDIT_TOOLBAR__BEGIN]=QPixmap( (const char**) edit_toolbar__begin_xpm); 
    pixmap_map_skin["edit_toolbar__begin"]=THEME_EDIT_TOOLBAR__BEGIN;
    pixmap_map[THEME_EDIT_TOOLBAR__CURSOR_FOLLOWS_PLAYBACK]=QPixmap( (const char**) edit_toolbar__cursor_follows_playback_xpm); 
    pixmap_map_skin["edit_toolbar__cursor_follows_playback"]=THEME_EDIT_TOOLBAR__CURSOR_FOLLOWS_PLAYBACK;
    pixmap_map[THEME_EDIT_TOOLBAR__CURSOR_FOLLOWS_PLAYBACK_PUSHED]=QPixmap( (const char**) edit_toolbar__cursor_follows_playback_pushed_xpm); 
    pixmap_map_skin["edit_toolbar__cursor_follows_playback_pushed"]=THEME_EDIT_TOOLBAR__CURSOR_FOLLOWS_PLAYBACK_PUSHED;
    pixmap_map[THEME_EDIT_TOOLBAR__CURSOR_STEPPING_DROPDOWN]=QPixmap( (const char**) edit_toolbar__cursor_stepping_dropdown_xpm); 
    pixmap_map_skin["edit_toolbar__cursor_stepping_dropdown"]=THEME_EDIT_TOOLBAR__CURSOR_STEPPING_DROPDOWN;
    pixmap_map[THEME_EDIT_TOOLBAR__CURSOR_STEPPING_DROPDOWN_BOTTOM]=QPixmap( (const char**) edit_toolbar__cursor_stepping_dropdown_bottom_xpm); 
    pixmap_map_skin["edit_toolbar__cursor_stepping_dropdown_bottom"]=THEME_EDIT_TOOLBAR__CURSOR_STEPPING_DROPDOWN_BOTTOM;
    pixmap_map[THEME_EDIT_TOOLBAR__CURSOR_STEPPING_DROPDOWN_TOP]=QPixmap( (const char**) edit_toolbar__cursor_stepping_dropdown_top_xpm); 
    pixmap_map_skin["edit_toolbar__cursor_stepping_dropdown_top"]=THEME_EDIT_TOOLBAR__CURSOR_STEPPING_DROPDOWN_TOP;
    pixmap_map[THEME_EDIT_TOOLBAR__CURSOR_STEPPING_ICON]=QPixmap( (const char**) edit_toolbar__cursor_stepping_icon_xpm); 
    pixmap_map_skin["edit_toolbar__cursor_stepping_icon"]=THEME_EDIT_TOOLBAR__CURSOR_STEPPING_ICON;
    pixmap_map[THEME_EDIT_TOOLBAR__EDIT_MENU]=QPixmap( (const char**) edit_toolbar__edit_menu_xpm); 
    pixmap_map_skin["edit_toolbar__edit_menu"]=THEME_EDIT_TOOLBAR__EDIT_MENU;
    pixmap_map[THEME_EDIT_TOOLBAR__EDIT_MENU_BOTTOM]=QPixmap( (const char**) edit_toolbar__edit_menu_bottom_xpm); 
    pixmap_map_skin["edit_toolbar__edit_menu_bottom"]=THEME_EDIT_TOOLBAR__EDIT_MENU_BOTTOM;
    pixmap_map[THEME_EDIT_TOOLBAR__EDIT_MENU_TOP]=QPixmap( (const char**) edit_toolbar__edit_menu_top_xpm); 
    pixmap_map_skin["edit_toolbar__edit_menu_top"]=THEME_EDIT_TOOLBAR__EDIT_MENU_TOP;
    pixmap_map[THEME_EDIT_TOOLBAR__END]=QPixmap( (const char**) edit_toolbar__end_xpm); 
    pixmap_map_skin["edit_toolbar__end"]=THEME_EDIT_TOOLBAR__END;
    pixmap_map[THEME_EDIT_TOOLBAR__MIDI_IN_CONFIG]=QPixmap( (const char**) edit_toolbar__midi_in_config_xpm); 
    pixmap_map_skin["edit_toolbar__midi_in_config"]=THEME_EDIT_TOOLBAR__MIDI_IN_CONFIG;
    pixmap_map[THEME_EDIT_TOOLBAR__MIDI_IN_CONFIG_PUSHED]=QPixmap( (const char**) edit_toolbar__midi_in_config_pushed_xpm); 
    pixmap_map_skin["edit_toolbar__midi_in_config_pushed"]=THEME_EDIT_TOOLBAR__MIDI_IN_CONFIG_PUSHED;
    pixmap_map[THEME_EDIT_TOOLBAR__PLAY_CURRENT_BLOCK]=QPixmap( (const char**) edit_toolbar__play_current_block_xpm); 
    pixmap_map_skin["edit_toolbar__play_current_block"]=THEME_EDIT_TOOLBAR__PLAY_CURRENT_BLOCK;
    pixmap_map[THEME_EDIT_TOOLBAR__PLAY_CURRENT_BLOCK_PUSHED]=QPixmap( (const char**) edit_toolbar__play_current_block_pushed_xpm); 
    pixmap_map_skin["edit_toolbar__play_current_block_pushed"]=THEME_EDIT_TOOLBAR__PLAY_CURRENT_BLOCK_PUSHED;
    pixmap_map[THEME_EDIT_TOOLBAR__PLAY_FROM_CURSOR]=QPixmap( (const char**) edit_toolbar__play_from_cursor_xpm); 
    pixmap_map_skin["edit_toolbar__play_from_cursor"]=THEME_EDIT_TOOLBAR__PLAY_FROM_CURSOR;
    pixmap_map[THEME_EDIT_TOOLBAR__PLAY_FROM_CURSOR_PUSHED]=QPixmap( (const char**) edit_toolbar__play_from_cursor_pushed_xpm); 
    pixmap_map_skin["edit_toolbar__play_from_cursor_pushed"]=THEME_EDIT_TOOLBAR__PLAY_FROM_CURSOR_PUSHED;
    pixmap_map[THEME_EDIT_TOOLBAR__POLY]=QPixmap( (const char**) edit_toolbar__poly_xpm); 
    pixmap_map_skin["edit_toolbar__poly"]=THEME_EDIT_TOOLBAR__POLY;
    pixmap_map[THEME_EDIT_TOOLBAR__POLY_ACTIVE]=QPixmap( (const char**) edit_toolbar__poly_active_xpm); 
    pixmap_map_skin["edit_toolbar__poly_active"]=THEME_EDIT_TOOLBAR__POLY_ACTIVE;
    pixmap_map[THEME_EDIT_TOOLBAR__SEPARATOR]=QPixmap( (const char**) edit_toolbar__separator_xpm); 
    pixmap_map_skin["edit_toolbar__separator"]=THEME_EDIT_TOOLBAR__SEPARATOR;
    pixmap_map[THEME_EDIT_TOOLBAR__SNAP_DROPDOWN]=QPixmap( (const char**) edit_toolbar__snap_dropdown_xpm); 
    pixmap_map_skin["edit_toolbar__snap_dropdown"]=THEME_EDIT_TOOLBAR__SNAP_DROPDOWN;
    pixmap_map[THEME_EDIT_TOOLBAR__SNAP_DROPDOWN_BOTTOM]=QPixmap( (const char**) edit_toolbar__snap_dropdown_bottom_xpm); 
    pixmap_map_skin["edit_toolbar__snap_dropdown_bottom"]=THEME_EDIT_TOOLBAR__SNAP_DROPDOWN_BOTTOM;
    pixmap_map[THEME_EDIT_TOOLBAR__SNAP_DROPDOWN_TOP]=QPixmap( (const char**) edit_toolbar__snap_dropdown_top_xpm); 
    pixmap_map_skin["edit_toolbar__snap_dropdown_top"]=THEME_EDIT_TOOLBAR__SNAP_DROPDOWN_TOP;
    pixmap_map[THEME_EDIT_TOOLBAR__SPACER]=QPixmap( (const char**) edit_toolbar__spacer_xpm); 
    pixmap_map_skin["edit_toolbar__spacer"]=THEME_EDIT_TOOLBAR__SPACER;
    pixmap_map[THEME_EDIT_TOOLBAR__VOLUME_MASK]=QPixmap( (const char**) edit_toolbar__volume_mask_xpm); 
    pixmap_map_skin["edit_toolbar__volume_mask"]=THEME_EDIT_TOOLBAR__VOLUME_MASK;
    pixmap_map[THEME_EDIT_TOOLBAR__VOLUME_MASK_ACTIVE]=QPixmap( (const char**) edit_toolbar__volume_mask_active_xpm); 
    pixmap_map_skin["edit_toolbar__volume_mask_active"]=THEME_EDIT_TOOLBAR__VOLUME_MASK_ACTIVE;
    pixmap_map[THEME_EDIT_TOOLBAR__VOLUME_MASK_LABEL]=QPixmap( (const char**) edit_toolbar__volume_mask_label_xpm); 
    pixmap_map_skin["edit_toolbar__volume_mask_label"]=THEME_EDIT_TOOLBAR__VOLUME_MASK_LABEL;
    pixmap_map[THEME_EDIT_TOOLBAR__VOLUME_MASK_LABEL_BOTTOM]=QPixmap( (const char**) edit_toolbar__volume_mask_label_bottom_xpm); 
    pixmap_map_skin["edit_toolbar__volume_mask_label_bottom"]=THEME_EDIT_TOOLBAR__VOLUME_MASK_LABEL_BOTTOM;
    pixmap_map[THEME_EDIT_TOOLBAR__VOLUME_MASK_LABEL_TOP]=QPixmap( (const char**) edit_toolbar__volume_mask_label_top_xpm); 
    pixmap_map_skin["edit_toolbar__volume_mask_label_top"]=THEME_EDIT_TOOLBAR__VOLUME_MASK_LABEL_TOP;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_BOTTOM]=QPixmap( (const char**) effect_panel_generic_bottom_xpm); 
    pixmap_map_skin["effect_panel_generic_bottom"]=THEME_EFFECT_PANEL_GENERIC_BOTTOM;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_BOTTOM_LEFT]=QPixmap( (const char**) effect_panel_generic_bottom_left_xpm); 
    pixmap_map_skin["effect_panel_generic_bottom_left"]=THEME_EFFECT_PANEL_GENERIC_BOTTOM_LEFT;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_BOTTOM_RIGHT]=QPixmap( (const char**) effect_panel_generic_bottom_right_xpm); 
    pixmap_map_skin["effect_panel_generic_bottom_right"]=THEME_EFFECT_PANEL_GENERIC_BOTTOM_RIGHT;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_LABEL]=QPixmap( (const char**) effect_panel_generic_label_xpm); 
    pixmap_map_skin["effect_panel_generic_label"]=THEME_EFFECT_PANEL_GENERIC_LABEL;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_LEFT]=QPixmap( (const char**) effect_panel_generic_left_xpm); 
    pixmap_map_skin["effect_panel_generic_left"]=THEME_EFFECT_PANEL_GENERIC_LEFT;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_RIGHT]=QPixmap( (const char**) effect_panel_generic_right_xpm); 
    pixmap_map_skin["effect_panel_generic_right"]=THEME_EFFECT_PANEL_GENERIC_RIGHT;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_SLIDER_BASE]=QPixmap( (const char**) effect_panel_generic_slider_base_xpm); 
    pixmap_map_skin["effect_panel_generic_slider_base"]=THEME_EFFECT_PANEL_GENERIC_SLIDER_BASE;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_SLIDER_GRABBER]=QPixmap( (const char**) effect_panel_generic_slider_grabber_xpm); 
    pixmap_map_skin["effect_panel_generic_slider_grabber"]=THEME_EFFECT_PANEL_GENERIC_SLIDER_GRABBER;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_SLIDER_LIGHT]=QPixmap( (const char**) effect_panel_generic_slider_light_xpm); 
    pixmap_map_skin["effect_panel_generic_slider_light"]=THEME_EFFECT_PANEL_GENERIC_SLIDER_LIGHT;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_TOP]=QPixmap( (const char**) effect_panel_generic_top_xpm); 
    pixmap_map_skin["effect_panel_generic_top"]=THEME_EFFECT_PANEL_GENERIC_TOP;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_TOP_LEFT]=QPixmap( (const char**) effect_panel_generic_top_left_xpm); 
    pixmap_map_skin["effect_panel_generic_top_left"]=THEME_EFFECT_PANEL_GENERIC_TOP_LEFT;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_TOP_RIGHT]=QPixmap( (const char**) effect_panel_generic_top_right_xpm); 
    pixmap_map_skin["effect_panel_generic_top_right"]=THEME_EFFECT_PANEL_GENERIC_TOP_RIGHT;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_VALUE]=QPixmap( (const char**) effect_panel_generic_value_xpm); 
    pixmap_map_skin["effect_panel_generic_value"]=THEME_EFFECT_PANEL_GENERIC_VALUE;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_VU_EMPTY]=QPixmap( (const char**) effect_panel_generic_vu_empty_xpm); 
    pixmap_map_skin["effect_panel_generic_vu_empty"]=THEME_EFFECT_PANEL_GENERIC_VU_EMPTY;
    pixmap_map[THEME_EFFECT_PANEL_GENERIC_VU_FILL]=QPixmap( (const char**) effect_panel_generic_vu_fill_xpm); 
    pixmap_map_skin["effect_panel_generic_vu_fill"]=THEME_EFFECT_PANEL_GENERIC_VU_FILL;
    pixmap_map[THEME_GLOBAL_TOOLBAR__ADD]=QPixmap( (const char**) global_toolbar__add_xpm); 
    pixmap_map_skin["global_toolbar__add"]=THEME_GLOBAL_TOOLBAR__ADD;
    pixmap_map[THEME_GLOBAL_TOOLBAR__ADD_ACTIVE]=QPixmap( (const char**) global_toolbar__add_active_xpm); 
    pixmap_map_skin["global_toolbar__add_active"]=THEME_GLOBAL_TOOLBAR__ADD_ACTIVE;
    pixmap_map[THEME_GLOBAL_TOOLBAR__BOTTOM_RIGHT_PIXMAP]=QPixmap( (const char**) global_toolbar__bottom_right_pixmap_xpm); 
    pixmap_map_skin["global_toolbar__bottom_right_pixmap"]=THEME_GLOBAL_TOOLBAR__BOTTOM_RIGHT_PIXMAP;
    pixmap_map[THEME_GLOBAL_TOOLBAR__COPY]=QPixmap( (const char**) global_toolbar__copy_xpm); 
    pixmap_map_skin["global_toolbar__copy"]=THEME_GLOBAL_TOOLBAR__COPY;
    pixmap_map[THEME_GLOBAL_TOOLBAR__COPY_ACTIVE]=QPixmap( (const char**) global_toolbar__copy_active_xpm); 
    pixmap_map_skin["global_toolbar__copy_active"]=THEME_GLOBAL_TOOLBAR__COPY_ACTIVE;
    pixmap_map[THEME_GLOBAL_TOOLBAR__COPY_LINK]=QPixmap( (const char**) global_toolbar__copy_link_xpm); 
    pixmap_map_skin["global_toolbar__copy_link"]=THEME_GLOBAL_TOOLBAR__COPY_LINK;
    pixmap_map[THEME_GLOBAL_TOOLBAR__COPY_LINK_ACTIVE]=QPixmap( (const char**) global_toolbar__copy_link_active_xpm); 
    pixmap_map_skin["global_toolbar__copy_link_active"]=THEME_GLOBAL_TOOLBAR__COPY_LINK_ACTIVE;
    pixmap_map[THEME_GLOBAL_TOOLBAR__ERASER]=QPixmap( (const char**) global_toolbar__eraser_xpm); 
    pixmap_map_skin["global_toolbar__eraser"]=THEME_GLOBAL_TOOLBAR__ERASER;
    pixmap_map[THEME_GLOBAL_TOOLBAR__ERASER_PUSHED]=QPixmap( (const char**) global_toolbar__eraser_pushed_xpm); 
    pixmap_map_skin["global_toolbar__eraser_pushed"]=THEME_GLOBAL_TOOLBAR__ERASER_PUSHED;
    pixmap_map[THEME_GLOBAL_TOOLBAR__HSPACER]=QPixmap( (const char**) global_toolbar__hspacer_xpm); 
    pixmap_map_skin["global_toolbar__hspacer"]=THEME_GLOBAL_TOOLBAR__HSPACER;
    pixmap_map[THEME_GLOBAL_TOOLBAR__LEFT]=QPixmap( (const char**) global_toolbar__left_xpm); 
    pixmap_map_skin["global_toolbar__left"]=THEME_GLOBAL_TOOLBAR__LEFT;
    pixmap_map[THEME_GLOBAL_TOOLBAR__RIGHT]=QPixmap( (const char**) global_toolbar__right_xpm); 
    pixmap_map_skin["global_toolbar__right"]=THEME_GLOBAL_TOOLBAR__RIGHT;
    pixmap_map[THEME_GLOBAL_TOOLBAR__SELECT]=QPixmap( (const char**) global_toolbar__select_xpm); 
    pixmap_map_skin["global_toolbar__select"]=THEME_GLOBAL_TOOLBAR__SELECT;
    pixmap_map[THEME_GLOBAL_TOOLBAR__SELECT_ACTIVE]=QPixmap( (const char**) global_toolbar__select_active_xpm); 
    pixmap_map_skin["global_toolbar__select_active"]=THEME_GLOBAL_TOOLBAR__SELECT_ACTIVE;
    pixmap_map[THEME_GLOBAL_TOOLBAR__SELECT_LINKED]=QPixmap( (const char**) global_toolbar__select_linked_xpm); 
    pixmap_map_skin["global_toolbar__select_linked"]=THEME_GLOBAL_TOOLBAR__SELECT_LINKED;
    pixmap_map[THEME_GLOBAL_TOOLBAR__SELECT_LINKED_PUSHED]=QPixmap( (const char**) global_toolbar__select_linked_pushed_xpm); 
    pixmap_map_skin["global_toolbar__select_linked_pushed"]=THEME_GLOBAL_TOOLBAR__SELECT_LINKED_PUSHED;
    pixmap_map[THEME_GLOBAL_TOOLBAR__UNLINK_SELECTED]=QPixmap( (const char**) global_toolbar__unlink_selected_xpm); 
    pixmap_map_skin["global_toolbar__unlink_selected"]=THEME_GLOBAL_TOOLBAR__UNLINK_SELECTED;
    pixmap_map[THEME_GLOBAL_TOOLBAR__UNLINK_SELECTED_PUSHED]=QPixmap( (const char**) global_toolbar__unlink_selected_pushed_xpm); 
    pixmap_map_skin["global_toolbar__unlink_selected_pushed"]=THEME_GLOBAL_TOOLBAR__UNLINK_SELECTED_PUSHED;
    pixmap_map[THEME_GLOBAL_TOOLBAR__ZOOM_BG]=QPixmap( (const char**) global_toolbar__zoom_bg_xpm); 
    pixmap_map_skin["global_toolbar__zoom_bg"]=THEME_GLOBAL_TOOLBAR__ZOOM_BG;
    pixmap_map[THEME_GLOBAL_TOOLBAR__ZOOM_FG]=QPixmap( (const char**) global_toolbar__zoom_fg_xpm); 
    pixmap_map_skin["global_toolbar__zoom_fg"]=THEME_GLOBAL_TOOLBAR__ZOOM_FG;
    pixmap_map[THEME_GLOBAL_TOOLBAR__ZOOM_GRABBER]=QPixmap( (const char**) global_toolbar__zoom_grabber_xpm); 
    pixmap_map_skin["global_toolbar__zoom_grabber"]=THEME_GLOBAL_TOOLBAR__ZOOM_GRABBER;
    pixmap_map[THEME_GLOBAL_TOOLBAR__ZOOM_ICON]=QPixmap( (const char**) global_toolbar__zoom_icon_xpm); 
    pixmap_map_skin["global_toolbar__zoom_icon"]=THEME_GLOBAL_TOOLBAR__ZOOM_ICON;
    pixmap_map[THEME_LEFT__MARGIN]=QPixmap( (const char**) left__margin_xpm); 
    pixmap_map_skin["left__margin"]=THEME_LEFT__MARGIN;
    pixmap_map[THEME_MIDDLE__SEPARATOR_BEGIN]=QPixmap( (const char**) middle__separator_begin_xpm); 
    pixmap_map_skin["middle__separator_begin"]=THEME_MIDDLE__SEPARATOR_BEGIN;
    pixmap_map[THEME_MIDDLE__SEPARATOR_CENTER]=QPixmap( (const char**) middle__separator_center_xpm); 
    pixmap_map_skin["middle__separator_center"]=THEME_MIDDLE__SEPARATOR_CENTER;
    pixmap_map[THEME_MIDDLE__SEPARATOR_END]=QPixmap( (const char**) middle__separator_end_xpm); 
    pixmap_map_skin["middle__separator_end"]=THEME_MIDDLE__SEPARATOR_END;
    pixmap_map[THEME_MIDDLE_SEPARATOR_END]=QPixmap( (const char**) middle_separator_end_xpm); 
    pixmap_map_skin["middle_separator_end"]=THEME_MIDDLE_SEPARATOR_END;
    pixmap_map[THEME_RACK_PANEL__JACK_FORBIDDEN]=QPixmap( (const char**) rack_panel__jack_forbidden_xpm); 
    pixmap_map_skin["rack_panel__jack_forbidden"]=THEME_RACK_PANEL__JACK_FORBIDDEN;
    pixmap_map[THEME_RACK_PANEL__JACK_IN]=QPixmap( (const char**) rack_panel__jack_in_xpm); 
    pixmap_map_skin["rack_panel__jack_in"]=THEME_RACK_PANEL__JACK_IN;
    pixmap_map[THEME_RACK_PANEL__JACK_OUT]=QPixmap( (const char**) rack_panel__jack_out_xpm); 
    pixmap_map_skin["rack_panel__jack_out"]=THEME_RACK_PANEL__JACK_OUT;
    pixmap_map[THEME_RACK_PLUGIN_TOP__BEGIN]=QPixmap( (const char**) rack_plugin_top__begin_xpm); 
    pixmap_map_skin["rack_plugin_top__begin"]=THEME_RACK_PLUGIN_TOP__BEGIN;
    pixmap_map[THEME_RACK_PLUGIN_TOP__END]=QPixmap( (const char**) rack_plugin_top__end_xpm); 
    pixmap_map_skin["rack_plugin_top__end"]=THEME_RACK_PLUGIN_TOP__END;
    pixmap_map[THEME_RACK_PLUGIN_TOP__INFO]=QPixmap( (const char**) rack_plugin_top__info_xpm); 
    pixmap_map_skin["rack_plugin_top__info"]=THEME_RACK_PLUGIN_TOP__INFO;
    pixmap_map[THEME_RACK_PLUGIN_TOP__INFO_PUSHED]=QPixmap( (const char**) rack_plugin_top__info_pushed_xpm); 
    pixmap_map_skin["rack_plugin_top__info_pushed"]=THEME_RACK_PLUGIN_TOP__INFO_PUSHED;
    pixmap_map[THEME_RACK_PLUGIN_TOP__MOVE_LEFT]=QPixmap( (const char**) rack_plugin_top__move_left_xpm); 
    pixmap_map_skin["rack_plugin_top__move_left"]=THEME_RACK_PLUGIN_TOP__MOVE_LEFT;
    pixmap_map[THEME_RACK_PLUGIN_TOP__MOVE_LEFT_PUSHED]=QPixmap( (const char**) rack_plugin_top__move_left_pushed_xpm); 
    pixmap_map_skin["rack_plugin_top__move_left_pushed"]=THEME_RACK_PLUGIN_TOP__MOVE_LEFT_PUSHED;
    pixmap_map[THEME_RACK_PLUGIN_TOP__MOVE_RIGHT]=QPixmap( (const char**) rack_plugin_top__move_right_xpm); 
    pixmap_map_skin["rack_plugin_top__move_right"]=THEME_RACK_PLUGIN_TOP__MOVE_RIGHT;
    pixmap_map[THEME_RACK_PLUGIN_TOP__MOVE_RIGHT_PUSHED]=QPixmap( (const char**) rack_plugin_top__move_right_pushed_xpm); 
    pixmap_map_skin["rack_plugin_top__move_right_pushed"]=THEME_RACK_PLUGIN_TOP__MOVE_RIGHT_PUSHED;
    pixmap_map[THEME_RACK_PLUGIN_TOP__PRESET]=QPixmap( (const char**) rack_plugin_top__preset_xpm); 
    pixmap_map_skin["rack_plugin_top__preset"]=THEME_RACK_PLUGIN_TOP__PRESET;
    pixmap_map[THEME_RACK_PLUGIN_TOP__PRESET_NAME]=QPixmap( (const char**) rack_plugin_top__preset_name_xpm); 
    pixmap_map_skin["rack_plugin_top__preset_name"]=THEME_RACK_PLUGIN_TOP__PRESET_NAME;
    pixmap_map[THEME_RACK_PLUGIN_TOP__PRESET_PUSHED]=QPixmap( (const char**) rack_plugin_top__preset_pushed_xpm); 
    pixmap_map_skin["rack_plugin_top__preset_pushed"]=THEME_RACK_PLUGIN_TOP__PRESET_PUSHED;
    pixmap_map[THEME_RACK_PLUGIN_TOP__REMOVE]=QPixmap( (const char**) rack_plugin_top__remove_xpm); 
    pixmap_map_skin["rack_plugin_top__remove"]=THEME_RACK_PLUGIN_TOP__REMOVE;
    pixmap_map[THEME_RACK_PLUGIN_TOP__REMOVE_PUSHED]=QPixmap( (const char**) rack_plugin_top__remove_pushed_xpm); 
    pixmap_map_skin["rack_plugin_top__remove_pushed"]=THEME_RACK_PLUGIN_TOP__REMOVE_PUSHED;
    pixmap_map[THEME_RACK_PLUGIN_TOP__SEPARATOR]=QPixmap( (const char**) rack_plugin_top__separator_xpm); 
    pixmap_map_skin["rack_plugin_top__separator"]=THEME_RACK_PLUGIN_TOP__SEPARATOR;
    pixmap_map[THEME_RACK_PLUGIN_TOP__SKIP]=QPixmap( (const char**) rack_plugin_top__skip_xpm); 
    pixmap_map_skin["rack_plugin_top__skip"]=THEME_RACK_PLUGIN_TOP__SKIP;
    pixmap_map[THEME_RACK_PLUGIN_TOP__SKIP_ACTIVE]=QPixmap( (const char**) rack_plugin_top__skip_active_xpm); 
    pixmap_map_skin["rack_plugin_top__skip_active"]=THEME_RACK_PLUGIN_TOP__SKIP_ACTIVE;
    pixmap_map[THEME_RACK_TOOLBAR__ADD_PLUGIN]=QPixmap( (const char**) rack_toolbar__add_plugin_xpm); 
    pixmap_map_skin["rack_toolbar__add_plugin"]=THEME_RACK_TOOLBAR__ADD_PLUGIN;
    pixmap_map[THEME_RACK_TOOLBAR__ADD_PLUGIN_PUSHED]=QPixmap( (const char**) rack_toolbar__add_plugin_pushed_xpm); 
    pixmap_map_skin["rack_toolbar__add_plugin_pushed"]=THEME_RACK_TOOLBAR__ADD_PLUGIN_PUSHED;
    pixmap_map[THEME_RACK_TOOLBAR__BEGIN]=QPixmap( (const char**) rack_toolbar__begin_xpm); 
    pixmap_map_skin["rack_toolbar__begin"]=THEME_RACK_TOOLBAR__BEGIN;
    pixmap_map[THEME_RACK_TOOLBAR__END]=QPixmap( (const char**) rack_toolbar__end_xpm); 
    pixmap_map_skin["rack_toolbar__end"]=THEME_RACK_TOOLBAR__END;
    pixmap_map[THEME_RACK_TOOLBAR__PRESET_FILE]=QPixmap( (const char**) rack_toolbar__preset_file_xpm); 
    pixmap_map_skin["rack_toolbar__preset_file"]=THEME_RACK_TOOLBAR__PRESET_FILE;
    pixmap_map[THEME_RACK_TOOLBAR__PRESET_FILE_PUSHED]=QPixmap( (const char**) rack_toolbar__preset_file_pushed_xpm); 
    pixmap_map_skin["rack_toolbar__preset_file_pushed"]=THEME_RACK_TOOLBAR__PRESET_FILE_PUSHED;
    pixmap_map[THEME_RACK_TOOLBAR__PRESET_ICON]=QPixmap( (const char**) rack_toolbar__preset_icon_xpm); 
    pixmap_map_skin["rack_toolbar__preset_icon"]=THEME_RACK_TOOLBAR__PRESET_ICON;
    pixmap_map[THEME_RACK_TOOLBAR__PRESET_LABEL]=QPixmap( (const char**) rack_toolbar__preset_label_xpm); 
    pixmap_map_skin["rack_toolbar__preset_label"]=THEME_RACK_TOOLBAR__PRESET_LABEL;
    pixmap_map[THEME_RACK_TOOLBAR__PRESET_LABEL_BOTTOM]=QPixmap( (const char**) rack_toolbar__preset_label_bottom_xpm); 
    pixmap_map_skin["rack_toolbar__preset_label_bottom"]=THEME_RACK_TOOLBAR__PRESET_LABEL_BOTTOM;
    pixmap_map[THEME_RACK_TOOLBAR__PRESET_LABEL_TOP]=QPixmap( (const char**) rack_toolbar__preset_label_top_xpm); 
    pixmap_map_skin["rack_toolbar__preset_label_top"]=THEME_RACK_TOOLBAR__PRESET_LABEL_TOP;
    pixmap_map[THEME_RACK_TOOLBAR__RACK_FOLLOW_CURSOR]=QPixmap( (const char**) rack_toolbar__rack_follow_cursor_xpm); 
    pixmap_map_skin["rack_toolbar__rack_follow_cursor"]=THEME_RACK_TOOLBAR__RACK_FOLLOW_CURSOR;
    pixmap_map[THEME_RACK_TOOLBAR__RACK_FOLLOW_CURSOR_ACTIVE]=QPixmap( (const char**) rack_toolbar__rack_follow_cursor_active_xpm); 
    pixmap_map_skin["rack_toolbar__rack_follow_cursor_active"]=THEME_RACK_TOOLBAR__RACK_FOLLOW_CURSOR_ACTIVE;
    pixmap_map[THEME_RACK_TOOLBAR__SEPARATOR]=QPixmap( (const char**) rack_toolbar__separator_xpm); 
    pixmap_map_skin["rack_toolbar__separator"]=THEME_RACK_TOOLBAR__SEPARATOR;
    pixmap_map[THEME_RACK_TOOLBAR__SHOW_BACK]=QPixmap( (const char**) rack_toolbar__show_back_xpm); 
    pixmap_map_skin["rack_toolbar__show_back"]=THEME_RACK_TOOLBAR__SHOW_BACK;
    pixmap_map[THEME_RACK_TOOLBAR__SHOW_BACK_ACTIVE]=QPixmap( (const char**) rack_toolbar__show_back_active_xpm); 
    pixmap_map_skin["rack_toolbar__show_back_active"]=THEME_RACK_TOOLBAR__SHOW_BACK_ACTIVE;
    pixmap_map[THEME_RACK_TOOLBAR__SHOW_FRONT]=QPixmap( (const char**) rack_toolbar__show_front_xpm); 
    pixmap_map_skin["rack_toolbar__show_front"]=THEME_RACK_TOOLBAR__SHOW_FRONT;
    pixmap_map[THEME_RACK_TOOLBAR__SHOW_FRONT_ACTIVE]=QPixmap( (const char**) rack_toolbar__show_front_active_xpm); 
    pixmap_map_skin["rack_toolbar__show_front_active"]=THEME_RACK_TOOLBAR__SHOW_FRONT_ACTIVE;
    pixmap_map[THEME_RACK_TOOLBAR__SPACER]=QPixmap( (const char**) rack_toolbar__spacer_xpm); 
    pixmap_map_skin["rack_toolbar__spacer"]=THEME_RACK_TOOLBAR__SPACER;
    pixmap_map[THEME_RACK_TOOLBAR__TRACK_DROPDOWN]=QPixmap( (const char**) rack_toolbar__track_dropdown_xpm); 
    pixmap_map_skin["rack_toolbar__track_dropdown"]=THEME_RACK_TOOLBAR__TRACK_DROPDOWN;
    pixmap_map[THEME_RACK_TOOLBAR__TRACK_DROPDOWN_BOTTOM]=QPixmap( (const char**) rack_toolbar__track_dropdown_bottom_xpm); 
    pixmap_map_skin["rack_toolbar__track_dropdown_bottom"]=THEME_RACK_TOOLBAR__TRACK_DROPDOWN_BOTTOM;
    pixmap_map[THEME_RACK_TOOLBAR__TRACK_DROPDOWN_TOP]=QPixmap( (const char**) rack_toolbar__track_dropdown_top_xpm); 
    pixmap_map_skin["rack_toolbar__track_dropdown_top"]=THEME_RACK_TOOLBAR__TRACK_DROPDOWN_TOP;
    pixmap_map[THEME_RIGHT__MARGIN]=QPixmap( (const char**) right__margin_xpm); 
    pixmap_map_skin["right__margin"]=THEME_RIGHT__MARGIN;
    pixmap_map[THEME_SCROLLBAR_ARROW_DOWN]=QPixmap( (const char**) scrollbar_arrow_down_xpm); 
    pixmap_map_skin["scrollbar_arrow_down"]=THEME_SCROLLBAR_ARROW_DOWN;
    pixmap_map[THEME_SCROLLBAR_ARROW_DOWN_PUSHED]=QPixmap( (const char**) scrollbar_arrow_down_pushed_xpm); 
    pixmap_map_skin["scrollbar_arrow_down_pushed"]=THEME_SCROLLBAR_ARROW_DOWN_PUSHED;
    pixmap_map[THEME_SCROLLBAR_ARROW_LEFT]=QPixmap( (const char**) scrollbar_arrow_left_xpm); 
    pixmap_map_skin["scrollbar_arrow_left"]=THEME_SCROLLBAR_ARROW_LEFT;
    pixmap_map[THEME_SCROLLBAR_ARROW_LEFT_PUSHED]=QPixmap( (const char**) scrollbar_arrow_left_pushed_xpm); 
    pixmap_map_skin["scrollbar_arrow_left_pushed"]=THEME_SCROLLBAR_ARROW_LEFT_PUSHED;
    pixmap_map[THEME_SCROLLBAR_ARROW_RIGHT]=QPixmap( (const char**) scrollbar_arrow_right_xpm); 
    pixmap_map_skin["scrollbar_arrow_right"]=THEME_SCROLLBAR_ARROW_RIGHT;
    pixmap_map[THEME_SCROLLBAR_ARROW_RIGHT_PUSHED]=QPixmap( (const char**) scrollbar_arrow_right_pushed_xpm); 
    pixmap_map_skin["scrollbar_arrow_right_pushed"]=THEME_SCROLLBAR_ARROW_RIGHT_PUSHED;
    pixmap_map[THEME_SCROLLBAR_ARROW_UP]=QPixmap( (const char**) scrollbar_arrow_up_xpm); 
    pixmap_map_skin["scrollbar_arrow_up"]=THEME_SCROLLBAR_ARROW_UP;
    pixmap_map[THEME_SCROLLBAR_ARROW_UP_PUSHED]=QPixmap( (const char**) scrollbar_arrow_up_pushed_xpm); 
    pixmap_map_skin["scrollbar_arrow_up_pushed"]=THEME_SCROLLBAR_ARROW_UP_PUSHED;
    pixmap_map[THEME_SCROLLBAR_GRABBER]=QPixmap( (const char**) scrollbar_grabber_xpm); 
    pixmap_map_skin["scrollbar_grabber"]=THEME_SCROLLBAR_GRABBER;
    pixmap_map[THEME_SCROLLBAR_H_BG]=QPixmap( (const char**) scrollbar_h_bg_xpm); 
    pixmap_map_skin["scrollbar_h_bg"]=THEME_SCROLLBAR_H_BG;
    pixmap_map[THEME_SCROLLBAR_V_BG]=QPixmap( (const char**) scrollbar_v_bg_xpm); 
    pixmap_map_skin["scrollbar_v_bg"]=THEME_SCROLLBAR_V_BG;
    pixmap_map[THEME_SIMPLER__BOTTOM]=QPixmap( (const char**) simpler__bottom_xpm); 
    pixmap_map_skin["simpler__bottom"]=THEME_SIMPLER__BOTTOM;
    pixmap_map[THEME_SIMPLER__DISPLAY_BOTTOM]=QPixmap( (const char**) simpler__display_bottom_xpm); 
    pixmap_map_skin["simpler__display_bottom"]=THEME_SIMPLER__DISPLAY_BOTTOM;
    pixmap_map[THEME_SIMPLER__DISPLAY_LEFT]=QPixmap( (const char**) simpler__display_left_xpm); 
    pixmap_map_skin["simpler__display_left"]=THEME_SIMPLER__DISPLAY_LEFT;
    pixmap_map[THEME_SIMPLER__DISPLAY_RIGHT]=QPixmap( (const char**) simpler__display_right_xpm); 
    pixmap_map_skin["simpler__display_right"]=THEME_SIMPLER__DISPLAY_RIGHT;
    pixmap_map[THEME_SIMPLER__EDIT]=QPixmap( (const char**) simpler__edit_xpm); 
    pixmap_map_skin["simpler__edit"]=THEME_SIMPLER__EDIT;
    pixmap_map[THEME_SIMPLER__EDIT_PUSHED]=QPixmap( (const char**) simpler__edit_pushed_xpm); 
    pixmap_map_skin["simpler__edit_pushed"]=THEME_SIMPLER__EDIT_PUSHED;
    pixmap_map[THEME_SIMPLER__KNOB]=QPixmap( (const char**) simpler__knob_xpm); 
    pixmap_map_skin["simpler__knob"]=THEME_SIMPLER__KNOB;
    pixmap_map[THEME_SIMPLER__KNOB_POS]=QPixmap( (const char**) simpler__knob_pos_xpm); 
    pixmap_map_skin["simpler__knob_pos"]=THEME_SIMPLER__KNOB_POS;
    pixmap_map[THEME_SIMPLER__KNOB_SEPARATOR]=QPixmap( (const char**) simpler__knob_separator_xpm); 
    pixmap_map_skin["simpler__knob_separator"]=THEME_SIMPLER__KNOB_SEPARATOR;
    pixmap_map[THEME_SIMPLER__LEFT]=QPixmap( (const char**) simpler__left_xpm); 
    pixmap_map_skin["simpler__left"]=THEME_SIMPLER__LEFT;
    pixmap_map[THEME_SIMPLER__LOAD]=QPixmap( (const char**) simpler__load_xpm); 
    pixmap_map_skin["simpler__load"]=THEME_SIMPLER__LOAD;
    pixmap_map[THEME_SIMPLER__LOAD_PUSHED]=QPixmap( (const char**) simpler__load_pushed_xpm); 
    pixmap_map_skin["simpler__load_pushed"]=THEME_SIMPLER__LOAD_PUSHED;
    pixmap_map[THEME_SIMPLER__RIGHT]=QPixmap( (const char**) simpler__right_xpm); 
    pixmap_map_skin["simpler__right"]=THEME_SIMPLER__RIGHT;
    pixmap_map[THEME_SIMPLER__TOP_LEFT]=QPixmap( (const char**) simpler__top_left_xpm); 
    pixmap_map_skin["simpler__top_left"]=THEME_SIMPLER__TOP_LEFT;
    pixmap_map[THEME_SIMPLER__TOP_RIGHT]=QPixmap( (const char**) simpler__top_right_xpm); 
    pixmap_map_skin["simpler__top_right"]=THEME_SIMPLER__TOP_RIGHT;
    pixmap_map[THEME_TOP__BPM_BOTTOM]=QPixmap( (const char**) top__bpm_bottom_xpm); 
    pixmap_map_skin["top__bpm_bottom"]=THEME_TOP__BPM_BOTTOM;
    pixmap_map[THEME_TOP__BPM_DISPLAY]=QPixmap( (const char**) top__bpm_display_xpm); 
    pixmap_map_skin["top__bpm_display"]=THEME_TOP__BPM_DISPLAY;
    pixmap_map[THEME_TOP__BPM_END]=QPixmap( (const char**) top__bpm_end_xpm); 
    pixmap_map_skin["top__bpm_end"]=THEME_TOP__BPM_END;
    pixmap_map[THEME_TOP__BPM_TOP]=QPixmap( (const char**) top__bpm_top_xpm); 
    pixmap_map_skin["top__bpm_top"]=THEME_TOP__BPM_TOP;
    pixmap_map[THEME_TOP__BPM_UPDOWN]=QPixmap( (const char**) top__bpm_updown_xpm); 
    pixmap_map_skin["top__bpm_updown"]=THEME_TOP__BPM_UPDOWN;
    pixmap_map[THEME_TOP__BUTTON_FASTFORWARD]=QPixmap( (const char**) top__button_fastforward_xpm); 
    pixmap_map_skin["top__button_fastforward"]=THEME_TOP__BUTTON_FASTFORWARD;
    pixmap_map[THEME_TOP__BUTTON_FASTFORWARD_ACTIVE]=QPixmap( (const char**) top__button_fastforward_active_xpm); 
    pixmap_map_skin["top__button_fastforward_active"]=THEME_TOP__BUTTON_FASTFORWARD_ACTIVE;
    pixmap_map[THEME_TOP__BUTTON_LOOP]=QPixmap( (const char**) top__button_loop_xpm); 
    pixmap_map_skin["top__button_loop"]=THEME_TOP__BUTTON_LOOP;
    pixmap_map[THEME_TOP__BUTTON_LOOP_ACTIVE]=QPixmap( (const char**) top__button_loop_active_xpm); 
    pixmap_map_skin["top__button_loop_active"]=THEME_TOP__BUTTON_LOOP_ACTIVE;
    pixmap_map[THEME_TOP__BUTTON_PAUSE]=QPixmap( (const char**) top__button_pause_xpm); 
    pixmap_map_skin["top__button_pause"]=THEME_TOP__BUTTON_PAUSE;
    pixmap_map[THEME_TOP__BUTTON_PAUSE_ACTIVE]=QPixmap( (const char**) top__button_pause_active_xpm); 
    pixmap_map_skin["top__button_pause_active"]=THEME_TOP__BUTTON_PAUSE_ACTIVE;
    pixmap_map[THEME_TOP__BUTTON_PLAY]=QPixmap( (const char**) top__button_play_xpm); 
    pixmap_map_skin["top__button_play"]=THEME_TOP__BUTTON_PLAY;
    pixmap_map[THEME_TOP__BUTTON_PLAY_ACTIVE]=QPixmap( (const char**) top__button_play_active_xpm); 
    pixmap_map_skin["top__button_play_active"]=THEME_TOP__BUTTON_PLAY_ACTIVE;
    pixmap_map[THEME_TOP__BUTTON_RECORD]=QPixmap( (const char**) top__button_record_xpm); 
    pixmap_map_skin["top__button_record"]=THEME_TOP__BUTTON_RECORD;
    pixmap_map[THEME_TOP__BUTTON_RECORD_ACTIVE]=QPixmap( (const char**) top__button_record_active_xpm); 
    pixmap_map_skin["top__button_record_active"]=THEME_TOP__BUTTON_RECORD_ACTIVE;
    pixmap_map[THEME_TOP__BUTTON_RECORD_AUTOMATIONS]=QPixmap( (const char**) top__button_record_automations_xpm); 
    pixmap_map_skin["top__button_record_automations"]=THEME_TOP__BUTTON_RECORD_AUTOMATIONS;
    pixmap_map[THEME_TOP__BUTTON_RECORD_AUTOMATIONS_ACTIVE]=QPixmap( (const char**) top__button_record_automations_active_xpm); 
    pixmap_map_skin["top__button_record_automations_active"]=THEME_TOP__BUTTON_RECORD_AUTOMATIONS_ACTIVE;
    pixmap_map[THEME_TOP__BUTTON_REWIND]=QPixmap( (const char**) top__button_rewind_xpm); 
    pixmap_map_skin["top__button_rewind"]=THEME_TOP__BUTTON_REWIND;
    pixmap_map[THEME_TOP__BUTTON_REWIND_ACTIVE]=QPixmap( (const char**) top__button_rewind_active_xpm); 
    pixmap_map_skin["top__button_rewind_active"]=THEME_TOP__BUTTON_REWIND_ACTIVE;
    pixmap_map[THEME_TOP__BUTTON_STOP]=QPixmap( (const char**) top__button_stop_xpm); 
    pixmap_map_skin["top__button_stop"]=THEME_TOP__BUTTON_STOP;
    pixmap_map[THEME_TOP__BUTTON_STOP_ACTIVE]=QPixmap( (const char**) top__button_stop_active_xpm); 
    pixmap_map_skin["top__button_stop_active"]=THEME_TOP__BUTTON_STOP_ACTIVE;
    pixmap_map[THEME_TOP__BUTTONS_BOTTOM]=QPixmap( (const char**) top__buttons_bottom_xpm); 
    pixmap_map_skin["top__buttons_bottom"]=THEME_TOP__BUTTONS_BOTTOM;
    pixmap_map[THEME_TOP__BUTTONS_BPM_SEPARATOR]=QPixmap( (const char**) top__buttons_bpm_separator_xpm); 
    pixmap_map_skin["top__buttons_bpm_separator"]=THEME_TOP__BUTTONS_BPM_SEPARATOR;
    pixmap_map[THEME_TOP__BUTTONS_TOP]=QPixmap( (const char**) top__buttons_top_xpm); 
    pixmap_map_skin["top__buttons_top"]=THEME_TOP__BUTTONS_TOP;
    pixmap_map[THEME_TOP__CONTROLS_END]=QPixmap( (const char**) top__controls_end_xpm); 
    pixmap_map_skin["top__controls_end"]=THEME_TOP__CONTROLS_END;
    pixmap_map[THEME_TOP__ICON_ADD]=QPixmap( (const char**) top__icon_add_xpm); 
    pixmap_map_skin["top__icon_add"]=THEME_TOP__ICON_ADD;
    pixmap_map[THEME_TOP__ICON_ADD_ACTIVATED]=QPixmap( (const char**) top__icon_add_activated_xpm); 
    pixmap_map_skin["top__icon_add_activated"]=THEME_TOP__ICON_ADD_ACTIVATED;
    pixmap_map[THEME_TOP__ICON_FILE]=QPixmap( (const char**) top__icon_file_xpm); 
    pixmap_map_skin["top__icon_file"]=THEME_TOP__ICON_FILE;
    pixmap_map[THEME_TOP__ICON_FILE_ACTIVATED]=QPixmap( (const char**) top__icon_file_activated_xpm); 
    pixmap_map_skin["top__icon_file_activated"]=THEME_TOP__ICON_FILE_ACTIVATED;
    pixmap_map[THEME_TOP__ICON_HELP]=QPixmap( (const char**) top__icon_help_xpm); 
    pixmap_map_skin["top__icon_help"]=THEME_TOP__ICON_HELP;
    pixmap_map[THEME_TOP__ICON_HELP_ACTIVATED]=QPixmap( (const char**) top__icon_help_activated_xpm); 
    pixmap_map_skin["top__icon_help_activated"]=THEME_TOP__ICON_HELP_ACTIVATED;
    pixmap_map[THEME_TOP__ICON_REDO]=QPixmap( (const char**) top__icon_redo_xpm); 
    pixmap_map_skin["top__icon_redo"]=THEME_TOP__ICON_REDO;
    pixmap_map[THEME_TOP__ICON_REDO_ACTIVATED]=QPixmap( (const char**) top__icon_redo_activated_xpm); 
    pixmap_map_skin["top__icon_redo_activated"]=THEME_TOP__ICON_REDO_ACTIVATED;
    pixmap_map[THEME_TOP__ICON_REDO_DISABLED]=QPixmap( (const char**) top__icon_redo_disabled_xpm); 
    pixmap_map_skin["top__icon_redo_disabled"]=THEME_TOP__ICON_REDO_DISABLED;
    pixmap_map[THEME_TOP__ICON_SETTINGS]=QPixmap( (const char**) top__icon_settings_xpm); 
    pixmap_map_skin["top__icon_settings"]=THEME_TOP__ICON_SETTINGS;
    pixmap_map[THEME_TOP__ICON_SETTINGS_ACTIVATED]=QPixmap( (const char**) top__icon_settings_activated_xpm); 
    pixmap_map_skin["top__icon_settings_activated"]=THEME_TOP__ICON_SETTINGS_ACTIVATED;
    pixmap_map[THEME_TOP__ICON_UNDO]=QPixmap( (const char**) top__icon_undo_xpm); 
    pixmap_map_skin["top__icon_undo"]=THEME_TOP__ICON_UNDO;
    pixmap_map[THEME_TOP__ICON_UNDO_ACTIVATED]=QPixmap( (const char**) top__icon_undo_activated_xpm); 
    pixmap_map_skin["top__icon_undo_activated"]=THEME_TOP__ICON_UNDO_ACTIVATED;
    pixmap_map[THEME_TOP__ICON_UNDO_DISABLED]=QPixmap( (const char**) top__icon_undo_disabled_xpm); 
    pixmap_map_skin["top__icon_undo_disabled"]=THEME_TOP__ICON_UNDO_DISABLED;
    pixmap_map[THEME_TOP__MARGIN_BOTTOM]=QPixmap( (const char**) top__margin_bottom_xpm); 
    pixmap_map_skin["top__margin_bottom"]=THEME_TOP__MARGIN_BOTTOM;
    pixmap_map[THEME_TOP__MARGIN_LEFT]=QPixmap( (const char**) top__margin_left_xpm); 
    pixmap_map_skin["top__margin_left"]=THEME_TOP__MARGIN_LEFT;
    pixmap_map[THEME_TOP__MARGIN_RIGHT]=QPixmap( (const char**) top__margin_right_xpm); 
    pixmap_map_skin["top__margin_right"]=THEME_TOP__MARGIN_RIGHT;
    pixmap_map[THEME_TOP__SWING_BEGIN]=QPixmap( (const char**) top__swing_begin_xpm); 
    pixmap_map_skin["top__swing_begin"]=THEME_TOP__SWING_BEGIN;
    pixmap_map[THEME_TOP__SWING_BOTTOM]=QPixmap( (const char**) top__swing_bottom_xpm); 
    pixmap_map_skin["top__swing_bottom"]=THEME_TOP__SWING_BOTTOM;
    pixmap_map[THEME_TOP__SWING_END]=QPixmap( (const char**) top__swing_end_xpm); 
    pixmap_map_skin["top__swing_end"]=THEME_TOP__SWING_END;
    pixmap_map[THEME_TOP__SWING_KNOB]=QPixmap( (const char**) top__swing_knob_xpm); 
    pixmap_map_skin["top__swing_knob"]=THEME_TOP__SWING_KNOB;
    pixmap_map[THEME_TOP__SWING_KNOB_POS]=QPixmap( (const char**) top__swing_knob_pos_xpm); 
    pixmap_map_skin["top__swing_knob_pos"]=THEME_TOP__SWING_KNOB_POS;
    pixmap_map[THEME_TOP__SWING_TOP]=QPixmap( (const char**) top__swing_top_xpm); 
    pixmap_map_skin["top__swing_top"]=THEME_TOP__SWING_TOP;
    pixmap_map[THEME_TOP__TAB_EDIT]=QPixmap( (const char**) top__tab_edit_xpm); 
    pixmap_map_skin["top__tab_edit"]=THEME_TOP__TAB_EDIT;
    pixmap_map[THEME_TOP__TAB_EDIT_ACTIVE]=QPixmap( (const char**) top__tab_edit_active_xpm); 
    pixmap_map_skin["top__tab_edit_active"]=THEME_TOP__TAB_EDIT_ACTIVE;
    pixmap_map[THEME_TOP__TAB_MIX]=QPixmap( (const char**) top__tab_mix_xpm); 
    pixmap_map_skin["top__tab_mix"]=THEME_TOP__TAB_MIX;
    pixmap_map[THEME_TOP__TAB_MIX_ACTIVE]=QPixmap( (const char**) top__tab_mix_active_xpm); 
    pixmap_map_skin["top__tab_mix_active"]=THEME_TOP__TAB_MIX_ACTIVE;
    pixmap_map[THEME_TOP__TAB_SONG]=QPixmap( (const char**) top__tab_song_xpm); 
    pixmap_map_skin["top__tab_song"]=THEME_TOP__TAB_SONG;
    pixmap_map[THEME_TOP__TAB_SONG_ACTIVE]=QPixmap( (const char**) top__tab_song_active_xpm); 
    pixmap_map_skin["top__tab_song_active"]=THEME_TOP__TAB_SONG_ACTIVE;
    pixmap_map[THEME_TOP__TABS_BUTTONS_SEPARATOR]=QPixmap( (const char**) top__tabs_buttons_separator_xpm); 
    pixmap_map_skin["top__tabs_buttons_separator"]=THEME_TOP__TABS_BUTTONS_SEPARATOR;
    pixmap_map[THEME_TRACK_PANEL__LABEL_BOTTOM]=QPixmap( (const char**) track_panel__label_bottom_xpm); 
    pixmap_map_skin["track_panel__label_bottom"]=THEME_TRACK_PANEL__LABEL_BOTTOM;
    pixmap_map[THEME_TRACK_PANEL__SWING_BASE]=QPixmap( (const char**) track_panel__swing_base_xpm); 
    pixmap_map_skin["track_panel__swing_base"]=THEME_TRACK_PANEL__SWING_BASE;
    pixmap_map[THEME_TRACK_PANEL__SWING_BOTTOM]=QPixmap( (const char**) track_panel__swing_bottom_xpm); 
    pixmap_map_skin["track_panel__swing_bottom"]=THEME_TRACK_PANEL__SWING_BOTTOM;
    pixmap_map[THEME_TRACK_PANEL__SWING_COMBO]=QPixmap( (const char**) track_panel__swing_combo_xpm); 
    pixmap_map_skin["track_panel__swing_combo"]=THEME_TRACK_PANEL__SWING_COMBO;
    pixmap_map[THEME_TRACK_PANEL__SWING_KNOB]=QPixmap( (const char**) track_panel__swing_knob_xpm); 
    pixmap_map_skin["track_panel__swing_knob"]=THEME_TRACK_PANEL__SWING_KNOB;
    pixmap_map[THEME_TRACK_PANEL__SWING_KNOB_POS]=QPixmap( (const char**) track_panel__swing_knob_pos_xpm); 
    pixmap_map_skin["track_panel__swing_knob_pos"]=THEME_TRACK_PANEL__SWING_KNOB_POS;
    pixmap_map[THEME_TRACK_PANEL__SWING_LABEL]=QPixmap( (const char**) track_panel__swing_label_xpm); 
    pixmap_map_skin["track_panel__swing_label"]=THEME_TRACK_PANEL__SWING_LABEL;
    pixmap_map[THEME_TRACK_PANEL__SWING_LOCAL]=QPixmap( (const char**) track_panel__swing_local_xpm); 
    pixmap_map_skin["track_panel__swing_local"]=THEME_TRACK_PANEL__SWING_LOCAL;
    pixmap_map[THEME_TRACK_PANEL__SWING_LOCAL_OFF]=QPixmap( (const char**) track_panel__swing_local_off_xpm); 
    pixmap_map_skin["track_panel__swing_local_off"]=THEME_TRACK_PANEL__SWING_LOCAL_OFF;
    pixmap_map[THEME_TRACK_PANEL__SWING_LOCAL_ON]=QPixmap( (const char**) track_panel__swing_local_on_xpm); 
    pixmap_map_skin["track_panel__swing_local_on"]=THEME_TRACK_PANEL__SWING_LOCAL_ON;
    pixmap_map[THEME_TRACK_PANEL__SWING_VALUE]=QPixmap( (const char**) track_panel__swing_value_xpm); 
    pixmap_map_skin["track_panel__swing_value"]=THEME_TRACK_PANEL__SWING_VALUE;

}

} //end of namespace

